"""empty message

Revision ID: 1a9c98823b6a
Revises: 2cb1fc2f9b2b
Create Date: 2015-07-16 15:10:01.912105

"""

# revision identifiers, used by Alembic.
revision = '1a9c98823b6a'
down_revision = '2cb1fc2f9b2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
