"""empty message

Revision ID: 1dc03b84aeb5
Revises: 1a9c98823b6a
Create Date: 2015-07-17 15:38:24.364649

"""

# revision identifiers, used by Alembic.
revision = '1dc03b84aeb5'
down_revision = '1a9c98823b6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    ### end Alembic commands ###
