"""empty message

Revision ID: 2cb1fc2f9b2b
Revises: 3c53f1e7f2b
Create Date: 2015-07-16 00:09:40.671761

"""

# revision identifiers, used by Alembic.
revision = '2cb1fc2f9b2b'
down_revision = '3c53f1e7f2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
