"""empty message

Revision ID: 34613a0defdd
Revises: bfa119def9
Create Date: 2015-07-27 09:52:52.633588

"""

# revision identifiers, used by Alembic.
revision = '34613a0defdd'
down_revision = 'bfa119def9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
