"""empty message

Revision ID: 43c63035a5f6
Revises: 40dce2d6a7f0
Create Date: 2015-07-08 16:34:40.799207

"""

# revision identifiers, used by Alembic.
revision = '43c63035a5f6'
down_revision = '40dce2d6a7f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=64), nullable=True))
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_phone', 'users')
    op.drop_index('ix_users_name', 'users')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    ### end Alembic commands ###
