"""empty message

Revision ID: 43fc9d5d5907
Revises: 456a945560f6
Create Date: 2015-07-06 14:50:12.042358

"""

# revision identifiers, used by Alembic.
revision = '43fc9d5d5907'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
