"""empty message

Revision ID: bfa119def9
Revises: 400ff4905521
Create Date: 2015-07-27 09:51:40.388450

"""

# revision identifiers, used by Alembic.
revision = 'bfa119def9'
down_revision = '400ff4905521'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
