"""empty message

Revision ID: cb69836906d
Revises: d320ca8ec13
Create Date: 2015-07-15 09:27:56.984070

"""

# revision identifiers, used by Alembic.
revision = 'cb69836906d'
down_revision = 'd320ca8ec13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
