"""empty message

Revision ID: d320ca8ec13
Revises: 43c63035a5f6
Create Date: 2015-07-13 11:53:28.838652

"""

# revision identifiers, used by Alembic.
revision = 'd320ca8ec13'
down_revision = '43c63035a5f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
