"""empty message

Revision ID: fc814e4e8c5
Revises: 43fc9d5d5907
Create Date: 2015-07-06 16:26:08.546175

"""

# revision identifiers, used by Alembic.
revision = 'fc814e4e8c5'
down_revision = '43fc9d5d5907'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
